export const ADD_PRODUCT = "ADD_PRODUCT";
export const MINUS_PRODUCT = "MINUS_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CALL_API = "CALL_API";
export const REMOVE_ALL_PRODUCT = "REMOVE_ALL_PRODUCT";